DROP TABLE IF EXISTS T_ITEMS;
CREATE TABLE IF NOT EXISTS T_ITEMS (
    NAME VARCHAR(255) NOT NULL,
    PROPERTIES INT NULL,
    TYPE VARCHAR(255) NULL,

    PRIMARY KEY (NAME)
);

DROP TABLE IF EXISTS T_USERS;
CREATE TABLE IF NOT EXISTS T_USERS (
    NAME VARCHAR(255) NOT NULL,
    PROPERTIES INT NULL,

    PRIMARY KEY(NAME)
);

DROP TABLE IF EXISTS T_ORDERS;
CREATE TABLE IF NOT EXISTS T_ORDERS (
    ID BIGINT UNSIGNED AUTOINCREMENT NOT NULL,
    USER VARCHAR(255) NULL,
    ITEM VARCHAR(255) NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (USER) REFERENCES T_USERS(NAME),
    FOREIGN KEY (ITEM) REFERENCES T_ITEMS(NAME)
);
