CREATE TABLE IF NOT EXISTS T_ITEMS (
    ITEM_NAME VARCHAR(255) NOT NULL,
    PROPERTIES INT NULL,
    TYPE VARCHAR(255) NULL,

    PRIMARY KEY (NAME)
);

CREATE TABLE IF NOT EXISTS T_USERS (
    USER_NAME VARCHAR(255) NOT NULL,
    PROPERTIES INT NULL,

    PRIMARY KEY(NAME)
);

CREATE TABLE IF NOT EXISTS T_ORDERS (
    ID_ORDER BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    USER_NAME VARCHAR(255) NULL,
    ITEM VARCHAR(255) NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (USER_NAME) REFERENCES T_USERS(USER_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ITEM) REFERENCES T_ITEMS(ITEM_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
